camunda:
  client:
    zeebe:
      defaults:
        stream-enabled: false
    auth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
    cluster-id: ${CLUSTER_ID}
    region: ${CLIENT_REGION}
    mode: ${CLIENT_MODE}